services:
  - type: web
    name: kahoot-api
    runtime: docker
    repo: https://github.com/Adrian-2004/KahootAdrian
    dockerfilePath: Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
